return {
	cmd = {
		"clangd",
		-- "--all-scopes-completion",
		"--background-index",
		-- "--clang-tidy=false",
		-- "--clang-tidy-checks=performance-*,bugprone-*,misc-*,google-*,modernize-*,readability-*,portability-*",
		"--completion-parse=auto",
		"--completion-style=bundled",
		"--enable-config",
		"--fallback-style=Google",
		"--function-arg-placeholders=true",
		"--header-insertion-decorators",
		"--header-insertion=never",
		"--log=verbose",
		"--pch-storage=memory",
		"--pretty",
		"--ranking-model=decision_forest",
		"-j=16",
	},
	filetypes = { "c", "cpp", "objc", "objcpp", "cuda" },
	root_markers = {
		".clangd",
		".clang-tidy",
		".clang-format",
		"compile_commands.json",
		"compile_flags.txt",
		"configure.ac",
		".git",
	},
}
