# vim:filetype=kitty
# vim:fdm=marker

# unmap
map cmd+f no_op
map alt+shift+h no_op
map alt+shift+l no_op
map cmd+shift+w no_op
map cmd+shift+d no_op
map ctrl+shift+r no_op
map cmd+enter no_op
map cmd+r no_op
map cmd+` no_op
map cmd+shift+` no_op

# kitty
map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5
map ctrl+shift+6 goto_tab 6
map ctrl+shift+7 goto_tab 7
map ctrl+shift+8 goto_tab 8
map ctrl+shift+9 goto_tab 9
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+n new_os_window
map ctrl+shift+o next_layout
#map ctrl+shift+f show_scrollback
map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right
map ctrl+shift+z toggle_layout stack

map ctrl+shift+up resize_window taller 1
map ctrl+shift+down resize_window shorter 1
map ctrl+shift+left resize_window narrower 1
map ctrl+shift+right resize_window wider 1

# tmux
map alt+1 combine : send_key ctrl+space : send_key 1
map alt+2 combine : send_key ctrl+space : send_key 2
map alt+3 combine : send_key ctrl+space : send_key 3
map alt+4 combine : send_key ctrl+space : send_key 4
map alt+5 combine : send_key ctrl+space : send_key 5
map alt+6 combine : send_key ctrl+space : send_key 6
map alt+7 combine : send_key ctrl+space : send_key 7
map alt+8 combine : send_key ctrl+space : send_key 8
map alt+9 combine : send_key ctrl+space : send_key 9
map alt+t combine : send_key ctrl+space : send_key c
map alt+w combine : send_key ctrl+space : send_key x
map ctrl+shift+[ combine : send_key ctrl+space : send_key {
map ctrl+shift+] combine : send_key ctrl+space : send_key }
map cmd+shift+w combine : send_key ctrl+space : send_key w
# map cmd+n combine : send_key ctrl+space : send_key "
map cmd+n combine : send_key ctrl+space : send_key i
map cmd+shift+n combine : send_key ctrl+space : send_key "
map alt+z combine : send_key ctrl+space : send_key z
map cmd+shift+h combine : send_key ctrl+space : send_key space

# vim
#map ctrl+s send_text all \e:wa\r
# map cmd+shift+r send_text all \e\e:OverseerQuickAction\r


# hints
#map ctrl+shift+p kitten hints --type path --program @
# map ctrl+shift+h kgitten hints --type hash --program @
#map ctrl+shift+d kitten hints --customize-processing ~/.config/kitty/helpers/custom_match.py --program -

