# 基础路径配置
music_directory    "/home/bianca/Music/"       # 你的音乐文件夹路径
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

# 网络设置
bind_to_address    "127.0.0.1"    # 仅允许本地连接
port               "6600"         # 默认端口

# 自动更新数据库
auto_update        "yes"

# 音频输出配置 (以 ALSA 为例)
#audio_output {
#    type            "alsa"
#    name            "My ALSA Device"
#}

# 如果你使用 PulseAudio，请用下面这段代替上面的 ALSA
 audio_output {
     type            "pulse"
     name            "pulse audio"
 }

# 为了在 ncmpcpp 中显示频谱图，需要开启这个输出
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
